Repository joshua1535/Guanaco-Tickets, pull requests merged in 2023-11, with the labels that each got.

#6 Fixing Register functionality
  Client/package-lock.json
  Client/src/pages/Register/RegisterForm.jsx
  Server/src/main/java/com/guanacobusiness/event_ticket_sales/configs/WebSecurityConfig.java
Labels: bug

#13 Deploy api
  Server/Dockerfile
  Server/gradlew
Labels: API

#19 Adding deployed database connection
  Client/src/API/Instance.js
  Server/src/main/resources/application.properties
Labels: enhancement, API

#22 Fixing profile pictures in Admin users and edit permit users pages
  Client/src/pages/Admin Users/AdminUsers.jsx
  Client/src/pages/Edit Permit Users/EditPermitUsers.jsx
  Client/src/pages/Register/RegisterForm.jsx
Labels: bug

#24 Fixing access for Event Permit page
  Client/src/App.jsx
Labels: bug

#30 My orders design
  Client/src/pages/My Orders/MyOrders.jsx
  Client/src/pages/My Tickets/MyTickets.jsx
Labels: enhancement

#32 Input qr code
  Client/src/pages/Ticket Validation/TicketValidation.jsx
  Client/src/pages/Ticket Validation/TicketValidation.module.css
Labels: enhancement

#31 Fixing Role behavior
  Client/package-lock.json
  Client/src/App.jsx
  Client/src/Components/Private/Private.jsx
  Client/src/Context/userContext.jsx
  Client/src/pages/Admin Users/AdminUsers.jsx
  Client/src/pages/Edit Permit Users/EditPermitUsers.jsx
  Client/src/pages/Edit Permit Users/EditPermitUsers.module.css
  Client/src/pages/Login/LoginForm.jsx
  Client/src/pages/My Tickets/MyTickets.jsx
  Client/src/pages/Register/RegisterForm.jsx
  Client/src/pages/Transfer Ticket/TransferTicket.jsx
  Server/Dockerfile
  Server/gradlew
  Server/src/main/java/com/guanacobusiness/event_ticket_sales/configs/WebSecurityConfig.java
  Server/src/main/resources/application.properties
  package-lock.json
Labels: bug

#33 Fixing Show My Tickets Page
  Client/src/API/Instance.js
  Client/src/pages/My Tickets/MyTickets.jsx
Labels: bug

#35 Fix cors
  Server/src/main/java/com/guanacobusiness/event_ticket_sales/configs/WebSecurityConfig.java
Labels: bug, API

#36 Fixing Pagination in Admin Users page
  Client/package-lock.json
  Client/src/pages/Admin Users/AdminUsers.jsx
Labels: bug

#37 FixingProfilePicture
  Client/src/pages/Admin Users/AdminUsers.jsx
  Client/src/pages/Edit Permit Users/EditPermitUsers.jsx
Labels: bug

#40 Fixing Register Button in Login Page
  Client/package-lock.json
  Client/src/pages/Login/LoginForm.jsx
  Client/src/pages/Register/RegisterForm.jsx
Labels: bug

#43 Fixing Redeem Ticket
  Client/src/Services/registerService.js
  Client/src/pages/My Tickets/MyTickets.jsx
  Client/src/pages/QRPage/QR.jsx
Labels: bug

#45 Adding Toast Notifications to Buy Tickets Page
  Client/package-lock.json
  Client/src/pages/BuyTicketPage/BuyTicketPage.jsx
Labels: enhancement

#47 Cleaning code in some pages
  Client/src/pages/Admin Users/AdminUsers.jsx
  Client/src/pages/Edit Permit Users/EditPermitUsers.jsx
Labels: bug

#50 Adding Users Table component for Admin Users page
  Client/src/Components/UsersTable.jsx
  Client/src/pages/Admin Users/AdminUsers.jsx
Labels: bug, enhancement

#52 Changing the Login Img
  Client/src/assets/loginimg.jpg
  Client/src/assets/loginimg.png
  Client/src/pages/Add Tiers/AddTiers.jsx
  Client/src/pages/Admin Users/AdminUsers.jsx
  Client/src/pages/Create Event/CreateEvent.jsx
  Client/src/pages/Error404/Error404Form.jsx
  Client/src/pages/Event Permits/EventPermits.jsx
  Client/src/pages/HomePage/HomePage.jsx
  Client/src/pages/Login/LoginForm.jsx
  Client/src/pages/Modify Event/ModifyEvent.jsx
  Client/src/pages/Modify Staff/ModifyStaff.jsx
  Client/src/pages/My Orders/MyOrders.jsx
  Client/src/pages/My Tickets/MyTickets.jsx
  Client/src/pages/Register/EmailConfirmation/EmailConfirmationForm.jsx
  Client/src/pages/Register/PasswordConfirmation/PasswordConfirmationForm.jsx
  Client/src/pages/Register/RegisterForm.jsx
  Client/src/pages/Stats/Stats.jsx
  Client/src/pages/Transfer Ticket/TransferTicket.jsx
  Client/src/pages/UpdatePassword/EmailConfirmation/EmailConfirmationForm.jsx
  Client/src/pages/UpdatePassword/UpdatePassword/UpdatePasswordForm.jsx
Labels: enhancement

#53 Creating TicketItem component for MyTickets page
  Client/src/Components/TicketItem.jsx
  Client/src/pages/My Tickets/MyTickets.jsx
Labels: enhancement

#55 Creating OrderTableComponent for My Orders page
  Client/src/Components/OrderTable.jsx
  Client/src/pages/My Orders/MyOrders.jsx
Labels: enhancement

#57 Creating Slider Card component for HomePage
  Client/package-lock.json
  Client/src/Components/SliderCards.jsx
  Client/src/pages/EventsPage/EventsPage.jsx
  Client/src/pages/HomePage/HomePage.jsx
Labels: enhancement

#58 Transfer ticket logic
  Client/src/Services/ticketService.js
  Client/src/pages/Transfer Ticket/TransferTicket.jsx
  Client/src/pages/Transfer Ticket/TransferTicket.module.css
Labels: enhancement

#64 Footer component
  Client/src/Components/Footer.jsx
  Client/src/pages/Add Tiers/AddTiers.jsx
  Client/src/pages/Admin Events/AdminEvents.jsx
  Client/src/pages/Admin Graphs/AdminGraphs.jsx
  Client/src/pages/BuyTicketPage/BuyTicketPage.jsx
  Client/src/pages/Create Event/CreateEvent.jsx
  Client/src/pages/Event Permits/EventPermits.jsx
  Client/src/pages/EventsPage/EventsPage.jsx
  Client/src/pages/HomePage/HomePage.jsx
  Client/src/pages/Modify Event/ModifyEvent.jsx
  Client/src/pages/My Orders/MyOrders.jsx
  Client/src/pages/My Tickets/MyTickets.jsx
Labels: enhancement

#66 Fixing Revoke Permit service in client
  Client/src/Services/permitService.js
Labels: bug

#68 Fixing Go Back Button in Error Page
  Client/src/pages/Error404/Error404Form.jsx
Labels: bug

#70 Fixing Edit Event functionalities
  Client/src/App.jsx
  Client/src/Services/eventService.js
  Client/src/pages/Event Permits/EventPermits.jsx
  Client/src/pages/Modify Event/ModifyEvent.jsx
  Client/src/pages/Modify Staff/ModifyStaff.jsx
Labels: bug

#71 Fixing Staff Ticket validator
  Client/src/pages/Modify Staff/ModifyStaff.jsx
Labels: bug

#75 Empty tickets and orders design
  Client/src/Components/Footer.jsx
  Client/src/assets/imgs/monoGif.gif
  Client/src/pages/My Orders/MyOrders.jsx
  Client/src/pages/My Tickets/MyTickets.jsx
Labels: bug, enhancement

#74 Now the Ticket Validation Page has Toast Notifications
  Client/src/pages/Ticket Validation/TicketValidation.jsx
Labels: enhancement

#77 Feature/fix admin events
  Client/src/Services/eventService.js
  Client/src/pages/Admin Events/AdminEvents.jsx
  Client/src/pages/HomePage/HomePage.jsx
Labels: bug, enhancement

#80 Change Login Design
  Client/src/pages/Login/LoginForm.jsx
Labels: bug

#82 Fixing Size pagination for events in homepage
  Client/src/pages/HomePage/HomePage.jsx
Labels: bug

#83 Feature/create header component
  Client/src/Components/Header/Header.jsx
  Client/src/Components/ProfileMenu/ProfileMenu.jsx
  Client/src/pages/Add Tiers/AddTiers.jsx
  Client/src/pages/Admin Events/AdminEvents.jsx
  Client/src/pages/Admin Graphs/AdminGraphs.jsx
  Client/src/pages/Admin Users/AdminUsers.jsx
  Client/src/pages/BuyTicketPage/BuyTicketPage.jsx
  Client/src/pages/Create Event/CreateEvent.jsx
  Client/src/pages/Edit Permit Users/EditPermitUsers.jsx
  Client/src/pages/Event Permits/EventPermits.jsx
  Client/src/pages/EventsPage/EventsPage.jsx
  Client/src/pages/HomePage/HomePage.jsx
  Client/src/pages/Modify Event/ModifyEvent.jsx
  Client/src/pages/Modify Staff/ModifyStaff.jsx
  Client/src/pages/My Events/MyEvents.jsx
  Client/src/pages/My Orders/MyOrders.jsx
  Client/src/pages/My Tickets/MyTickets.jsx
  Client/src/pages/QRPage/QR.jsx
  Client/src/pages/Receive Ticket/ReceiveTicket.jsx
  Client/src/pages/Stats/Stats.jsx
  Client/src/pages/Ticket Validation/TicketValidation.jsx
  Client/src/pages/Transfer Ticket/TransferTicket.jsx
Labels: bug, enhancement

#87 Fixing Validate Transfered Ticket and add location in created event
  Client/.gitignore
  Client/package-lock.json
  Client/src/App.jsx
  Client/src/Components/Header/Header.jsx
  Client/src/Components/TicketItem.jsx
  Client/src/Services/registerService.js
  Client/src/main.jsx
  Client/src/pages/Add Tiers/AddTiers.jsx
  Client/src/pages/Modify Event/ModifyEvent.jsx
  Client/src/pages/Transfer Ticket/TransferTicket.jsx
  Client/vite.config.js
Labels: bug
